export const POKEMONS_LOADED = 'POKEMONS_LOADED';
export const POKEMONS_FAILED = 'POKEMONS_FAILED';

export const POKEMON_LOADED = 'POKEMON_LOADED';
export const POKEMON_FAILED = 'POKEMON_FAILED';

export const NEXT_PAGE = 'NEXT_PAGE';
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE';